# Generated by Django 3.1.1 on 2020-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sms',
            field=models.TextField(max_length=444),
        ),
    ]
